export const ORDERS = [
  {
    image: "...",
    name: "Chaos Hoodie",
    variant: "Black / XL",
    orderNumber: "#URBN-78241",
    date: "May 24, 2025",
    status: "Shipped",
    price: "$89.00",
  },
  {
    image: "...",
    name: "Fragment Tee",
    variant: "Black / L",
    orderNumber: "#URBN-78240",
    date: "May 20, 2025",
    status: "Shipped",
    price: "$45.00",
  },
  {
    image: "...",
    name: "URBN Snapback",
    variant: "Black / O/S",
    orderNumber: "#URBN-78239",
    date: "May 13, 2025",
    status: "Shipped",
    price: "$35.00",
  },
  {
    image: "...",
    name: "Void Jacket",
    variant: "Black / XL",
    orderNumber: "#URBN-78238",
    date: "May 11, 2025",
    status: "Shipped",
    price: "$89.00",
  },
];
