export const reviews = [
  {
    id: "1",
    productId: "1",
    author: "John Doe",
    rating: 5,
    max: 5,
    body: "Great product!",
    createdAt: "2022-01-01",
    verified: true,
  },
  {
    id: "2",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "3",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "4",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "5",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "6",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "7",
    productId: "1",
    author: "Jane Doe",
    rating: 1,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "8",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "9",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
  {
    id: "10",
    productId: "1",
    author: "Jane Doe",
    rating: 3,
    max: 5,
    body: "Good product!",
    createdAt: "2022-01-01",
    verified: false,
  },
];
